export { default as BrandStudioView } from './BrandStudioView.jsx';
export { default as useBrandStudio } from './useBrandStudio.js';
export { default as LogoSchemes } from './LogoSchemes.jsx';
export { default as PreviewGeral } from './PreviewGeral.jsx';
export { default as BrandGlobalEditor } from './BrandGlobalEditor.jsx';
export { default as PlanTabsEditor } from './PlanTabsEditor.jsx';
export { default as ModuleEditor } from './ModuleEditor.jsx';
export { validateBrandConfig } from './validateBrandConfig.js';
export { BRAND_SCHEMA, BRAND_SCHEMA_VERSION } from './schema.js';
export { registerModule, getModule, listModules, getSchema, validateAgainstModules, normalizeModules } from './schemaRegistry.js';
export { default as previewValidate } from './previewValidator.js';
export { default as processResponse } from './responseProcessor.js';
export { enterPreviewMode, exitPreviewMode } from '../../shared/hooks/useBrandAppearance.js';
export { listPresets, getPreset, savePreset, deletePreset, duplicatePreset, toggleFavoritePreset, exportPreset, importPreset, getPresetCategories, OFFICIAL_PRESETS } from './presets.js';
export { getPlanTheme, getPlanThemeConfig, listPlanThemes, resolveBrandForPlan } from './planThemes.js';
